In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
import pandas as pd

df = pd.read_csv(r"C:\Users\91850\Downloads\Human_Resource_Data_Analysis-main\Human_Resource_Data_Analysis-main\data\HR-Employee-Attrition.csv")

In [12]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [13]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [14]:
row = list(df[df['YearsWithCurrManager'].isnull()].loc[:'YearsWithCurrManager'].index)

In [15]:
row

[]

In [16]:
df.drop(row,axis=0,inplace=True)

In [17]:
df.shape

(1470, 35)

In [18]:
df['count'] = 1

In [19]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [20]:
gender=df[['Gender','count']].groupby('Gender').sum()
gender

        count
Gender
Female    588
Male      882

In [24]:
gender.to_csv(r"C:\Users\91850\Downloads\Human_Resource_Data_Analysis-main\Human_Resource_Data_Analysis-main\data\HR_gender.csv",index=False,header=True)

In [ ]:
age = df[['Age','count']].groupby('Age').sum()
age

     count
Age
18       8
19       9
20      11
21      11
22      15
23      14
24      26
25      23
26      40
27      49
28      47
29      65
30      55
31      68
32      56
33      57
34      76
35      77
36      65
37      48
38      56
39      43
40      54
41      39
42      43
43      32
44      32
45      37
46      31
47      24
48      19
49      25
50      31
51      18
52      17
53      18
54      18
55      22
56      14
57       3
58      14
59       8
60       5

In [ ]:
age.to_csv("C:\\Users\\idipa\\Downloads\\HR_Age.csv",index=False,header=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(1416, 39)

In [ ]:
df['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', 'TravelRarely'],
      dtype=object)

In [ ]:
df['BusinessTravel'].replace('TravelRarely','Travel_Rarely',inplace=True)

In [ ]:
df['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [ ]:
for each in df.select_dtypes(include=['object']).columns:
    print(f"{each} : {df[each].unique()}")

EmpID : ['RM297' 'RM302' 'RM458' ... 'RM537' 'RM880' 'RM1210']
AgeGroup : ['18-25' '26-35' '36-45' '46-55' '55+']
Attrition : ['Yes' 'No']
BusinessTravel : ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
Department : ['Research & Development' 'Sales' 'Human Resources']
EducationField : ['Life Sciences' 'Medical' 'Marketing' 'Technical Degree' 'Other'
 'Human Resources']
Gender : ['Male' 'Female']
JobRole : ['Laboratory Technician' 'Sales Representative' 'Research Scientist'
 'Human Resources' 'Manufacturing Director' 'Sales Executive'
 'Healthcare Representative' 'Research Director' 'Manager']
MaritalStatus : ['Single' 'Divorced' 'Married']
SalarySlab : ['Upto 5k' '5k-10k' '10k-15k' '15k+']
Over18 : ['Y']
OverTime : ['No' 'Yes']

In [ ]:
df.to_csv("C:\\Users\\idipa\\Downloads\\HR_Analytics_.csv",index=False,header=True)